frontend-dolce-margarita/package-lock.json, frontend-dolce-margarita/package.json, frontend-dolce-margarita/src/App.js, frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/RellenoDeParedesDeHuevoCheckbox.js, frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/cargaDeDatos.js, frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/cargaDeDatos.scss
Página de carga de datos básicas con los campos de formularios compartidos entre los 3 formatos de chocolate.
=> Pagina carga datos

frontend-dolce-margarita/package-lock.json, frontend-dolce-margarita/package.json, frontend-dolce-margarita/src/App.js, frontend-dolce-margarita/src/componentes/home/Home.js, frontend-dolce-margarita/src/componentes/home/homepage.scss, frontend-dolce-margarita/src/componentes/loginAdmin/LoginAdmin.js, frontend-dolce-margarita/src/componentes/loginAdmin/loginAdmin.scss, frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/RellenoDeParedesDeHuevoCheckbox.js, frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/cargaDeDatos.js, frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/cargaDeDatos.scss
Agrego pagina de inicio del admin con las 3 cards para cargar un chocolate: Figura, Huevo o Bomboneria
=> Agregando cards de formatos en admin

frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/RellenoDeParedesDeHuevoCheckbox.js, frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/cargaDeDatos.js, frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/cargaDeDatos.scss
Muestra los campos correspondientes según el formato seleccionado.
Guarda el el estado del componente los valores cargados
=> Carga de datos de huevo y bombones

frontend-dolce-margarita/src/componentes/armadoDePedido/DatosDeHuevoParaPedido.js, frontend-dolce-margarita/src/componentes/armadoDePedido/ModalArmadoDePedido.js, frontend-dolce-margarita/src/componentes/armadoDePedido/modalArmadoDePedido.scss, frontend-dolce-margarita/src/componentes/listadoDeProductos/ListadoDeProductos.js
=> Modal armado de pedido

frontend-dolce-margarita/package.json, frontend-dolce-margarita/src/App.js, frontend-dolce-margarita/src/componentes/home/Home.js, frontend-dolce-margarita/src/componentes/home/moldes.js, frontend-dolce-margarita/src/componentes/listadoDeProductos/ListadoDeProductos.js, frontend-dolce-margarita/src/componentes/listadoDeProductos/listado-hasta-que-mica-levante-el-back.js, frontend-dolce-margarita/src/componentes/listadoDeProductos/listadoDeProductos.scss, frontend-dolce-margarita/src/servicios/servicio.js
Agrega el servicio en el front para hacer las requests de los productos dependiendo al que fue seleccionado en la página del Home.
Por ahora los datos estas harcodeados. Van a ser reemplazados cuando se cree el controller
=> Servicio frontend

frontend-dolce-margarita/src/App.js, frontend-dolce-margarita/src/componentes/armadoDePedido/ModalArmadoDePedido.js, frontend-dolce-margarita/src/componentes/confirmacionDePedido/ConfirmacionDePedido.js, frontend-dolce-margarita/src/componentes/confirmacionDePedido/confirmacion-de-pedido.scss, frontend-dolce-margarita/src/componentes/listadoDeProductos/ListadoDeProductos.js
=> Pagina confirmacion de pedido

frontend-dolce-margarita/src/componentes/home/homepage.scss
=> Arreglo estilos de las cartas del home

frontend-dolce-margarita/src/componentes/loginAdmin/LoginAdmin.js, frontend-dolce-margarita/src/componentes/loginAdmin/loginAdmin.scss
=> Vista login admin

frontend-dolce-margarita/src/componentes/loginAdmin/LoginAdmin.js, frontend-dolce-margarita/src/servicios/servicioLogin.js
Cuando un admin se loggea correctamente es enviado a la página de carga de datos
=> Frontend Login Admins

frontend-dolce-margarita/src/componentes/home/Home.js, frontend-dolce-margarita/src/componentes/home/homepage.scss
=> Agrego boton de login de admin en la Home principal

backend/app/controllers/productos_controller.rb, backend/app/models/producto.rb, backend/app/serializers/producto_serializer.rb, backend/spec/controllers/productos_controller_spec.rb
Se valida que estén todos los campos necesarios a la hora de crear un producto via productos_controller
=> Validaciones post producto

frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/cargaDeDatos.js, frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/cargaDeDatos.scss
=> Carga imagenes frontend

frontend-dolce-margarita/src/componentes/indexPedidos/IndexPedidos.js, frontend-dolce-margarita/src/componentes/indexPedidos/indexPedidos.scss, frontend-dolce-margarita/src/componentes/indexPedidos/pedido/InformacionPedido.js
=> Filtrado por nombre de cliente

backend/app/controllers/pedidos_controller.rb, backend/config/routes.rb, backend/db/seeds.rb, frontend-dolce-margarita/src/componentes/indexPedidos/IndexPedidos.js, frontend-dolce-margarita/src/servicios/ServicioPedidos.js
Se obtienen los pedidos reales desde el backend para mostrarlos en el index de pedidos
=> Obtener pedidos desde backend

backend/Gemfile, backend/app/controllers/productos_controller.rb, backend/app/models/producto.rb, backend/app/serializers/producto_serializer.rb, backend/app/uploaders/picture_uploader.rb, backend/config/environment.rb, backend/db/migrate/20190911205657_columnas_de_producto.rb, backend/db/schema.rb, frontend-dolce-margarita/src/componentes/listadoDeProductos/ListadoDeProductos.js, frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/cargaDeDatos.js, frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/cargaDeDatos.scss, frontend-dolce-margarita/src/servicios/ServicioCargaProducto.js
Se persisten las imagenes cuando cargamos un producto. El frontend sigue usando la imagen por default hasta que descubramos como mandarla desde el backend
=> Backend imagenes

backend/app/controllers/pedidos_controller.rb, backend/app/models/pedido.rb, backend/db/seeds.rb, frontend-dolce-margarita/src/componentes/indexPedidos/IndexPedidos.js, frontend-dolce-margarita/src/componentes/indexPedidos/indexPedidos.scss, frontend-dolce-margarita/src/componentes/indexPedidos/pedido/InformacionPedido.js, frontend-dolce-margarita/src/componentes/loginAdmin/LoginAdmin.js
=> Filtra por estado

backend/db/seeds.rb, frontend-dolce-margarita/src/componentes/indexPedidos/IndexPedidos.js, frontend-dolce-margarita/src/componentes/indexPedidos/indexPedidos.scss, frontend-dolce-margarita/src/componentes/indexPedidos/pedido/InformacionPedido.js, frontend-dolce-margarita/src/componentes/indexPedidos/pedido/LabelEstadoPedido.js, frontend-dolce-margarita/src/servicios/ServicioPedidos.js
Se agregan labels a cada pedido que indican su estado. 
Se pueden cancelar pedidos que están en espera o siendo preparados
=> Labels estado pedidos y cancelacion

frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/cargaDeDatos.js
Arreglo bug de carga de huevos. No se estaba enviando el tamaño al backend
=> Bug fix: Carga huevos

frontend-dolce-margarita/src/App.js, frontend-dolce-margarita/src/componentes/loginAdmin/PedidosOCargaDeDatos.js, frontend-dolce-margarita/src/componentes/loginAdmin/pedidosOCargaDeDatos.scss, frontend-dolce-margarita/src/productosARealizar/ProductosARealizar.js, frontend-dolce-margarita/src/productosARealizar/productosARealizar.scss
Mostrando mensaje de error cuando se apreta el boton calcular y no hay ningun producto seleccionado. Por ahora los productos están hardcodeados. Hay que agregar el endpoint para traerlos desde el controller
=> Vista cantidad a hacer por producto

backend/app/controllers/pedidos_controller.rb, backend/app/controllers/productos_controller.rb, backend/app/models/producto.rb, backend/config/routes.rb, backend/spec/controllers/pedidos_controller_spec.rb, backend/spec/controllers/productos_controller_spec.rb, backend/spec/rails_helper.rb
Agrego endpoint y logica en el PedidosController para saber cuantos productos con un cierto nombre y de cierto tipo de chocolate hay que realizar. Agrego ruta para obtener los nombres de los productos disponibles
=> Backend cantidad a hacer por producto

frontend-dolce-margarita/src/componentes/listadoDeProductos/ListadoDeProductos.js, frontend-dolce-margarita/src/productosARealizar/ProductosARealizar.js, frontend-dolce-margarita/src/productosARealizar/productosARealizar.scss, frontend-dolce-margarita/src/servicios/ServicioPedidos.js, frontend-dolce-margarita/src/servicios/servicio.js
integracion Frontend-Backend. Se calcula para un producto y un tipo de chocolate cuantos pedidos faltan hacer
=> Calculo pedidos restantes

frontend-dolce-margarita/src/componentes/edicionProducto/ModalEdicionProducto.js, frontend-dolce-margarita/src/componentes/edicionProducto/modalArmadoDePedido.scss, frontend-dolce-margarita/src/componentes/listadoDeProductos/ListadoDeProductos.js, frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/cargaDeDatos.js
=> agrego modal para edicion de producto

backend/app/controllers/productos_controller.rb, backend/config/routes.rb, backend/spec/controllers/productos_controller_spec.rb, frontend-dolce-margarita/src/App.js, frontend-dolce-margarita/src/componentes/edicionProducto/ModalEdicionProducto.js, frontend-dolce-margarita/src/componentes/listadoDeProductos/ListadoDeProductos.js, frontend-dolce-margarita/src/servicios/ServicioEdicionProducto.js
Integración del backend y frontend de edición de un producto. De un producto se pueden editar el nombre, el precio, el peso, la descripción y el tamaño en el caso de los huevos
=> Backend editar producto

frontend-dolce-margarita/src/componentes/armadoDePedido/ModalArmadoDePedido.js, frontend-dolce-margarita/src/componentes/confirmacionDePedido/ConfirmacionDePedido.js, frontend-dolce-margarita/src/componentes/home/Home.js, frontend-dolce-margarita/src/componentes/home/moldes.js, frontend-dolce-margarita/src/componentes/indexPedidos/IndexPedidos.js, frontend-dolce-margarita/src/componentes/indexPedidos/pedido/InformacionPedido.js, frontend-dolce-margarita/src/constantes.js, frontend-dolce-margarita/src/productosARealizar/ProductosARealizar.js
Extraigo constantes del frontend a un archivo en comun
=> Extraer constantes

backend/app/controllers/productos_controller.rb, backend/config/routes.rb, backend/spec/controllers/productos_controller_spec.rb, frontend-dolce-margarita/src/componentes/listadoDeProductos/ListadoDeProductos.js, frontend-dolce-margarita/src/componentes/listadoDeProductos/listadoDeProductos.scss, frontend-dolce-margarita/src/servicios/ServicioEliminarProducto.js
=> Eliminar producto [Backend & Frontend]

frontend-dolce-margarita/src/componentes/listadoDeProductos/ListadoDeProductos.js, frontend-dolce-margarita/src/componentes/listadoDeProductos/listadoDeProductos.scss
=> Nuevos estilos de cartas en index de productos

frontend-dolce-margarita/src/App.js, frontend-dolce-margarita/src/componentes/listadoDeProductos/ListadoDeProductos.js, frontend-dolce-margarita/src/componentes/navbar/Navbar.js, frontend-dolce-margarita/src/componentes/navbar/navbar.scss, frontend-dolce-margarita/src/componentes/paginaCargaDeDatos/cargaDeDatos.js, frontend-dolce-margarita/src/servicios/ServicioCargaProducto.js
Tareas realizadas:
- Cuando un admin carga un producto se lo redirige a la pagina de listado de productos 
- Cambio de estilos en el nav bar
- Se agrega boton de usuario al navbar. Si el admin está logeade, se le redirige al index del admin.
Si no, se le redirige a la página de logeo de admin 
- Se agrega boton de deslogeo del admin en caso de que esté logeade
=> Redireccionamiento post carga producto

backend/db/seeds.rb
Seed posta de productos. Faltan los pedidos
=> Seed posta
